### PR TITLE
Don't get notifications for followed accounts

### PR DESCRIPTION
**Pull request by akalipetis**
Currently, if you follow all captains, you end up taking notifications from 67 people - that's too much to be default IMO

### CODE REVIEW

**Comment by alexellis** [comment]
Hey @akalipetis thanks for contributing. Please could you make this part of the config.example.py file and then set it up as an additional flag with a default of `True`?

Let me know if you need help with the code.

**Comment by akalipetis** [comment]
Hey @alexellis - I just updated the code to use the change introduced in eb6c411bd5ddfbc8e267e1850446bdaed55694b6 - let me know what you think 😄

**Comment by alexellis** [comment]
Have you tested both variants `True`/`False`?

**Comment by akalipetis** [comment]
Yes, both are working fine 👍

**Comment by alexellis** [comment]
Merged. 👍 thanks!

**Pull request merged**
